#!/bin/env shell
CCP_BASEOS=debian
BASE_IMAGE_OS=${CCP_BASEOS}
CCP_PGVERSION=11
CCP_PG_FULLVERSION=11.15
CCP_PATRONI_VERSION=2.1.3
CCP_BACKREST_VERSION=2.36
CCP_VERSION=3.0.0
CCP_POSTGIS_VERSION=3.1
PACKAGER=apt
DOCKERBASEREGISTRY=docker.io/
CCP_IMAGE_TAG=${CCP_BASEOS}-${CCP_PG_FULLVERSION}-${CCP_VERSION}
CCP_POSTGIS_IMAGE_TAG=${CCP_BASEOS}-${CCP_PG_FULLVERSION}-${CCP_POSTGIS_VERSION}-${CCP_VERSION}
CCP_IMAGE_PREFIX=zhonghl003
export CCP_IMAGE_TAG \
    CCP_POSTGIS_IMAGE_TAG \
    CCP_IMAGE_PREFIX \
    CCP_PGVERSION \
    CCP_PG_FULLVERSION \
    CCP_PATRONI_VERSION \
    CCP_BACKREST_VERSION \
    CCP_VERSION \
    PACKAGER \
    DOCKERBASEREGISTRY \
    BASE_IMAGE_OS \
    CCP_BASEOS
